destination: /var/www/html/web
title: El Doctor del Desierto
description: El Doctor del Desierto
author: Jaime Hidalgo
logo: http://aboutashu.com/hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/jaimehrubiks
about: El Doctor del Desierto
disqus_shortname: jaimehrubiks
google_analytics: UA-79779892-1
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Resume
      url: '#'
      icon: fa-graduation-cap
    - text: Github
      url: https://github.com/jaimehrubiks
      icon: fa-github
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed

social:
    - icon: fa-facebook
      link: '#'
    - icon: fa-skype
      link: 'jaime-h'
    - icon: fa-twitter
      link: 'http://twitter.com/jaimehrubiks'
    - icon: fa-linkedin
      link: '#'
    - icon: fa-stack-exchange
      link: '#'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "/web"
baseurl: "/web"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
